name: Build and Archive

on:
  push:
    branches: [ test ] # 监听test分支的push

jobs:
  build-and-archive:
    runs-on: ubuntu-latest
    steps:
    # 拉取最新代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 设置node版本
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '22.12.0'
        cache: 'yarn'

    # 缓存依赖
    - name: Cache Yarn dependencies
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

     # 安装依赖
    - name: Install dependencies
      run: yarn install --frozen-lockfile

    # 构建项目
    - name: Build project
      run: yarn build

    # 部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # 使用内置的令牌
        publish_dir: ./dist # 项目构建产物的目录
        publish_branch: deploy # 指定要部署到的独立分支
        force_orphan: true  # 每次部署创建孤立提交，清空历史
        full_commit_message: "Deploy: ${{ github.event.head_commit.message }}" # 部署时的提交信息

    # 存档产物
    # - name: Archive production build
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: vue-dist # 存档名称
    #     path: dist/ # 存档dist目录
    #     retention-days: 7 # 存档保留天数（默认90天）

    # 成功时发送的邮件
    - name: Send success mail
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: "构建成功"
        html_body: |
          <h2>构建成功！🎉</h2>
          <p>项目 <strong>${{ github.repository }}</strong> 的分支 <strong>${{ github.ref_name }}</strong> 已成功构建。</p>
          <p>执行者: ${{ github.actor }}</p>
          <p>提交信息: ${{ github.event.head_commit.message }}</p>
          <p>详情请查看：<a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">GitHub Actions运行记录</a></p>
        to: 15797954826@163.com,1754551816@qq.com
        from: GitHub Actions Bot

    # 失败时发送的邮件
    - name: Send failure mail
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: "构建失败"
        html_body: |
          <h2>构建失败！⚠️</h2>
          <p>项目 <strong>${{ github.repository }}</strong> 的分支 <strong>${{ github.ref_name }}</strong> 构建失败，请及时检查！</p>
          <p>执行者: ${{ github.actor }}</p>
          <p>提交信息: ${{ github.event.head_commit.message }}</p>
          <p>详情请查看：<a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">GitHub Actions运行记录</a></p>
        to: 15797954826@163.com,1754551816@qq.com
        from: GitHub Actions Bot